import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { relationshipHealth, summarizePipeline } from '../src/lib/domain.js';

const root=join(fileURLToPath(new URL('..',import.meta.url)),'public');
const now=Date.now();const iso=(offset=0)=>new Date(now+offset).toISOString();const uid=()=>crypto.randomUUID();
const workspaces=[
  {id:'ws-pmg',name:'PartnerMarket Global',slug:'partnermarket-global',description:'Primary partnership and commercial CRM',timezone:'Europe/Amsterdam',currency:'EUR',color:'#0f766e',member_role:'admin',is_default:1},
  {id:'ws-gdc',name:'Golden Dragon Capital',slug:'golden-dragon-capital',description:'Investor and fundraising relationship database',timezone:'Asia/Singapore',currency:'USD',color:'#7559bd',member_role:'admin',is_default:0},
];
const users=[{id:'u1',name:'Alex de Vries',email:'alex@example.com',role:'admin',is_default:1},{id:'u2',name:'Siska Anita Sari',email:'siska@example.com',role:'manager',is_default:0},{id:'u3',name:'Commercial Team',email:'team@example.com',role:'member',is_default:0}];
const organizations=[
  {id:'o1',workspace_id:'ws-pmg',name:'Nusantara Distribution Group',industry:'FMCG Distribution',type:'prospect',status:'active',country:'Indonesia',city:'Jakarta',website:'https://example.com',account_tier:'strategic',territory:'Southeast Asia',owner_id:'u1',owner_name:'Alex de Vries',relationship_score:78,annual_value:750000,last_contact_at:iso(-5*864e5),next_follow_up_at:iso(1*864e5)},
  {id:'o2',workspace_id:'ws-pmg',name:'Benelux Retail Partners',industry:'Retail',type:'partner',status:'active',country:'Netherlands',city:'Amsterdam',account_tier:'key',territory:'Benelux',owner_id:'u1',owner_name:'Alex de Vries',relationship_score:65,annual_value:380000,last_contact_at:iso(-18*864e5),next_follow_up_at:iso(2*864e5)},
  {id:'o3',workspace_id:'ws-pmg',name:'Singapore Market Access',industry:'Consulting',type:'client',status:'active',country:'Singapore',city:'Singapore',account_tier:'standard',territory:'APAC',owner_id:'u2',owner_name:'Siska Anita Sari',relationship_score:88,annual_value:180000,last_contact_at:iso(-2*864e5)},
  {id:'o4',workspace_id:'ws-gdc',name:'Pacific Ventures',industry:'Venture Capital',type:'investor',status:'active',country:'Singapore',city:'Singapore',account_tier:'strategic',territory:'APAC',owner_id:'u1',owner_name:'Alex de Vries',relationship_score:81,annual_value:0,last_contact_at:iso(-4*864e5),next_follow_up_at:iso(3*864e5)},
];
const contacts=[
  {id:'c1',workspace_id:'ws-pmg',organization_id:'o1',organization_name:'Nusantara Distribution Group',first_name:'Maya',last_name:'Santoso',job_title:'Commercial Director',email:'maya@example.com',phone:'+62 21 555 0101',preferred_channel:'whatsapp',lifecycle_stage:'opportunity',status:'active',owner_id:'u1',owner_name:'Alex de Vries',relationship_score:82,source:'Referral',consent_status:'legitimate_interest',last_contact_at:iso(-3*864e5),next_follow_up_at:iso(-2*3600e3),notes:'Interested in cross-border distribution partnerships.',tags:['distribution','indonesia']},
  {id:'c2',workspace_id:'ws-pmg',organization_id:'o2',organization_name:'Benelux Retail Partners',first_name:'Thomas',last_name:'de Jong',job_title:'Category Manager',email:'thomas@example.com',phone:'+31 20 555 0133',preferred_channel:'email',lifecycle_stage:'qualified',status:'active',owner_id:'u1',owner_name:'Alex de Vries',relationship_score:57,source:'Event',consent_status:'consented',last_contact_at:iso(-22*864e5),next_follow_up_at:iso(1*864e5),notes:'Needs a proposal for Q4 retail activation.',tags:['retail','benelux']},
  {id:'c3',workspace_id:'ws-pmg',organization_id:'o3',organization_name:'Singapore Market Access',first_name:'Amelia',last_name:'Tan',job_title:'Managing Partner',email:'amelia@example.com',phone:'+65 6555 0102',preferred_channel:'meeting',lifecycle_stage:'customer',status:'active',owner_id:'u2',owner_name:'Siska Anita Sari',relationship_score:91,source:'Network',consent_status:'consented',last_contact_at:iso(-1*864e5),next_follow_up_at:iso(6*864e5),notes:'Active market entry client.',tags:['singapore','client']},
  {id:'c4',workspace_id:'ws-pmg',organization_id:'o1',organization_name:'Nusantara Distribution Group',first_name:'Rizky',last_name:'Pratama',job_title:'Head of Operations',email:'rizky@example.com',preferred_channel:'call',lifecycle_stage:'qualified',status:'active',owner_id:'u1',owner_name:'Alex de Vries',relationship_score:31,source:'Referral',consent_status:'unknown',last_contact_at:iso(-79*864e5),notes:'Operational stakeholder; relationship needs attention.',tags:['operations']},
  {id:'c5',workspace_id:'ws-gdc',organization_id:'o4',organization_name:'Pacific Ventures',first_name:'Daniel',last_name:'Lim',job_title:'Investment Director',email:'daniel@example.com',preferred_channel:'linkedin',lifecycle_stage:'opportunity',status:'active',owner_id:'u1',owner_name:'Alex de Vries',relationship_score:84,source:'Investor network',consent_status:'legitimate_interest',last_contact_at:iso(-4*864e5),next_follow_up_at:iso(3*864e5),tags:['investor','series-a']},
];
const activities=[
  {id:'a1',workspace_id:'ws-pmg',contact_id:'c1',organization_id:'o1',user_id:'u1',user_name:'Alex de Vries',contact_name:'Maya Santoso',organization_name:'Nusantara Distribution Group',type:'meeting',direction:'outbound',subject:'Distribution partnership discovery',body:'Discussed national coverage, channel mix and launch economics. Maya requested a phased proposal.',outcome:'Positive',sentiment:'positive',next_step:'Send phased commercial proposal',occurred_at:iso(-3*864e5)},
  {id:'a2',workspace_id:'ws-pmg',contact_id:'c3',organization_id:'o3',user_id:'u2',user_name:'Siska Anita Sari',contact_name:'Amelia Tan',organization_name:'Singapore Market Access',type:'email',direction:'outbound',subject:'Market entry weekly update',body:'Shared current retailer conversations and next-week priorities.',outcome:'Client updated',sentiment:'positive',occurred_at:iso(-1*864e5)},
  {id:'a3',workspace_id:'ws-pmg',contact_id:'c2',organization_id:'o2',user_id:'u1',user_name:'Alex de Vries',contact_name:'Thomas de Jong',organization_name:'Benelux Retail Partners',type:'call',direction:'outbound',subject:'Retail activation scope',body:'Thomas confirmed interest but needs the budget split by market.',outcome:'Proposal requested',sentiment:'neutral',next_step:'Prepare localized budget',occurred_at:iso(-22*864e5)},
  {id:'a4',workspace_id:'ws-gdc',contact_id:'c5',organization_id:'o4',user_id:'u1',user_name:'Alex de Vries',contact_name:'Daniel Lim',organization_name:'Pacific Ventures',type:'linkedin',direction:'outbound',subject:'Series A opportunity introduction',body:'Introduced the company and confirmed sector relevance.',outcome:'Deck requested',sentiment:'positive',occurred_at:iso(-4*864e5)},
];
const deals=[
  {id:'d1',workspace_id:'ws-pmg',name:'Indonesia distribution launch',organization_id:'o1',organization_name:'Nusantara Distribution Group',primary_contact_id:'c1',contact_name:'Maya Santoso',owner_id:'u1',owner_name:'Alex de Vries',stage:'proposal',value:420000,currency:'EUR',probability:55,expected_close_date:iso(35*864e5).slice(0,10),next_step:'Deliver phased proposal'},
  {id:'d2',workspace_id:'ws-pmg',name:'Benelux retail activation',organization_id:'o2',organization_name:'Benelux Retail Partners',primary_contact_id:'c2',contact_name:'Thomas de Jong',owner_id:'u1',owner_name:'Alex de Vries',stage:'qualified',value:180000,currency:'EUR',probability:30,expected_close_date:iso(55*864e5).slice(0,10),next_step:'Agree localized budget'},
  {id:'d3',workspace_id:'ws-pmg',name:'Singapore market entry retainer',organization_id:'o3',organization_name:'Singapore Market Access',primary_contact_id:'c3',contact_name:'Amelia Tan',owner_id:'u2',owner_name:'Siska Anita Sari',stage:'won',value:95000,currency:'EUR',probability:100,expected_close_date:iso(-10*864e5).slice(0,10),closed_at:iso(-12*864e5)},
  {id:'d4',workspace_id:'ws-gdc',name:'Series A investor process',organization_id:'o4',organization_name:'Pacific Ventures',primary_contact_id:'c5',contact_name:'Daniel Lim',owner_id:'u1',owner_name:'Alex de Vries',stage:'discovery',value:5000000,currency:'USD',probability:40,expected_close_date:iso(80*864e5).slice(0,10),next_step:'Share investor deck'},
];
const tasks=[
  {id:'t1',workspace_id:'ws-pmg',title:'Finish Indonesia proposal',description:'Complete pricing, rollout phases and governance.',contact_id:'c1',organization_id:'o1',deal_id:'d1',assignee_id:'u1',assignee_name:'Alex de Vries',contact_name:'Maya Santoso',organization_name:'Nusantara Distribution Group',deal_name:'Indonesia distribution launch',priority:'urgent',status:'in_progress',due_at:iso(-3*3600e3),task_type:'task',recurring_rule:'none'},
  {id:'t2',workspace_id:'ws-pmg',title:'Prepare Benelux budget split',contact_id:'c2',organization_id:'o2',deal_id:'d2',assignee_id:'u1',assignee_name:'Alex de Vries',contact_name:'Thomas de Jong',organization_name:'Benelux Retail Partners',priority:'high',status:'open',due_at:iso(1*864e5),task_type:'research',recurring_rule:'none'},
  {id:'t3',workspace_id:'ws-pmg',title:'Weekly client update',contact_id:'c3',organization_id:'o3',assignee_id:'u2',assignee_name:'Siska Anita Sari',contact_name:'Amelia Tan',organization_name:'Singapore Market Access',priority:'medium',status:'open',due_at:iso(3*864e5),task_type:'email',recurring_rule:'weekly'},
  {id:'t4',workspace_id:'ws-gdc',title:'Review investor deck',contact_id:'c5',organization_id:'o4',deal_id:'d4',assignee_id:'u1',assignee_name:'Alex de Vries',contact_name:'Daniel Lim',organization_name:'Pacific Ventures',priority:'high',status:'open',due_at:iso(1*864e5),task_type:'research',recurring_rule:'none'},
];
const followUps=[
  {id:'f1',workspace_id:'ws-pmg',title:'Send phased distribution proposal',contact_id:'c1',organization_id:'o1',deal_id:'d1',owner_id:'u1',owner_name:'Alex de Vries',contact_name:'Maya Santoso',organization_name:'Nusantara Distribution Group',deal_name:'Indonesia distribution launch',channel:'email',status:'open',priority:'urgent',due_at:iso(-2*3600e3),cadence:'none',notes:'Include national rollout assumptions.'},
  {id:'f2',workspace_id:'ws-pmg',title:'Call about Q4 activation budget',contact_id:'c2',organization_id:'o2',deal_id:'d2',owner_id:'u1',owner_name:'Alex de Vries',contact_name:'Thomas de Jong',organization_name:'Benelux Retail Partners',channel:'call',status:'open',priority:'high',due_at:iso(4*3600e3),cadence:'none'},
  {id:'f3',workspace_id:'ws-pmg',title:'Monthly steering meeting',contact_id:'c3',organization_id:'o3',owner_id:'u2',owner_name:'Siska Anita Sari',contact_name:'Amelia Tan',organization_name:'Singapore Market Access',channel:'meeting',status:'open',priority:'medium',due_at:iso(5*864e5),cadence:'monthly'},
  {id:'f4',workspace_id:'ws-gdc',title:'Send Series A deck',contact_id:'c5',organization_id:'o4',deal_id:'d4',owner_id:'u1',owner_name:'Alex de Vries',contact_name:'Daniel Lim',organization_name:'Pacific Ventures',channel:'email',status:'open',priority:'high',due_at:iso(3*864e5),cadence:'none'},
];

const emailSenders=[
  {id:'es-pmg',workspace_id:'ws-pmg',email_address:'info@partnermarketglobal.com',display_name:'PartnerMarket Global',reply_to:'info@partnermarketglobal.com',domain:'partnermarketglobal.com',is_default:1,is_active:1},
  {id:'es-pmg-gdc',workspace_id:'ws-pmg',email_address:'info@goldendragoncapital.co',display_name:'Golden Dragon Capital',reply_to:'info@goldendragoncapital.co',domain:'goldendragoncapital.co',is_default:0,is_active:1},
  {id:'es-pmg-dv',workspace_id:'ws-pmg',email_address:'info@devriessalesconsultancy.com',display_name:'De Vries Sales Consultancy',reply_to:'info@devriessalesconsultancy.com',domain:'devriessalesconsultancy.com',is_default:0,is_active:1},
  {id:'es-gdc',workspace_id:'ws-gdc',email_address:'info@goldendragoncapital.co',display_name:'Golden Dragon Capital',reply_to:'info@goldendragoncapital.co',domain:'goldendragoncapital.co',is_default:1,is_active:1},
  {id:'es-gdc-pmg',workspace_id:'ws-gdc',email_address:'info@partnermarketglobal.com',display_name:'PartnerMarket Global',reply_to:'info@partnermarketglobal.com',domain:'partnermarketglobal.com',is_default:0,is_active:1},
  {id:'es-gdc-dv',workspace_id:'ws-gdc',email_address:'info@devriessalesconsultancy.com',display_name:'De Vries Sales Consultancy',reply_to:'info@devriessalesconsultancy.com',domain:'devriessalesconsultancy.com',is_default:0,is_active:1},
];
const emailMessages=[];

function body(req){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>data+=c);req.on('end',()=>{try{resolve(data?JSON.parse(data):{});}catch(e){reject(e);}});});}
function respond(res,status,payload,type='application/json; charset=utf-8'){res.writeHead(status,{'content-type':type,'cache-control':'no-store'});res.end(type.startsWith('application/json')?JSON.stringify(payload):payload);}
function workspace(req){return req.headers['x-workspace-id']||'ws-pmg';}
function visible(list,ws){return list.filter(x=>x.workspace_id===ws);}
function enrichCounts(org,ws){return {...org,contact_count:visible(contacts,ws).filter(c=>c.organization_id===org.id).length,open_tasks:visible(tasks,ws).filter(t=>t.organization_id===org.id&&!['completed','cancelled'].includes(t.status)).length,open_follow_ups:visible(followUps,ws).filter(f=>f.organization_id===org.id&&['open','snoozed'].includes(f.status)).length,pipeline_value:visible(deals,ws).filter(d=>d.organization_id===org.id&&d.stage!=='lost').reduce((s,d)=>s+d.value,0)};}
function contactOut(c,ws){return {...c,activity_count:visible(activities,ws).filter(a=>a.contact_id===c.id).length,open_follow_ups:visible(followUps,ws).filter(f=>f.contact_id===c.id&&['open','snoozed'].includes(f.status)).length,open_tasks:visible(tasks,ws).filter(t=>t.contact_id===c.id&&!['completed','cancelled'].includes(t.status)).length,open_deal_value:visible(deals,ws).filter(d=>d.primary_contact_id===c.id&&!['won','lost'].includes(d.stage)).reduce((s,d)=>s+d.value,0)};}

async function handleApi(req,res,url){const ws=workspace(req);const p=url.pathname.split('/').filter(Boolean);const method=req.method;
  if(p[1]==='me')return respond(res,200,{user:users[0],workspace:workspaces.find(w=>w.id===ws)||workspaces[0],workspaces,permissions:{can_write:true,can_manage:true,can_admin:true}});
  if(p[1]==='users')return respond(res,200,users);
  if(p[1]==='dashboard'){
    const cs=visible(contacts,ws),os=visible(organizations,ws),ds=visible(deals,ws),ts=visible(tasks,ws),fs=visible(followUps,ws),as=visible(activities,ws);const pipe=summarizePipeline(ds);
    const days=Array.from({length:14},(_,i)=>{const d=new Date(now-(13-i)*864e5);const key=d.toISOString().slice(0,10);return{day:key,count:as.filter(a=>a.occurred_at.slice(0,10)===key).length};});
    const health={strong:cs.filter(c=>c.relationship_score>=80).length,healthy:cs.filter(c=>c.relationship_score>=55&&c.relationship_score<80).length,needs_attention:cs.filter(c=>c.relationship_score>=35&&c.relationship_score<55).length,at_risk:cs.filter(c=>c.relationship_score<35).length};
    return respond(res,200,{counts:{contacts:cs.length,organizations:os.length,overdue_tasks:ts.filter(t=>!['completed','cancelled'].includes(t.status)&&new Date(t.due_at)<new Date()).length,overdue_follow_ups:fs.filter(f=>['open','snoozed'].includes(f.status)&&new Date(f.snoozed_until||f.due_at)<new Date()).length,follow_ups_today:fs.filter(f=>['open','snoozed'].includes(f.status)&&new Date(f.snoozed_until||f.due_at).toDateString()===new Date().toDateString()).length,activities_30d:as.length},pipeline:{total_value:pipe.totalValue,weighted_value:pipe.weightedValue,won_value:pipe.wonValue,win_rate:pipe.winRate},stages:Object.entries(pipe.byStage).map(([stage,v])=>({stage,...v})),activity_by_day:days,tasks:ts.filter(t=>!['completed','cancelled'].includes(t.status)).slice(0,10),follow_ups:fs.filter(f=>['open','snoozed'].includes(f.status)).map(f=>({...f,effective_due_at:f.snoozed_until||f.due_at})).slice(0,10),recent_activities:as.sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)).slice(0,12),health,sources:[],stale_contacts:cs.filter(c=>!c.last_contact_at||new Date(c.last_contact_at)<new Date(now-60*864e5)).slice(0,8)});
  }
  if(p[1]==='agenda')return respond(res,200,{follow_ups:visible(followUps,ws).filter(f=>['open','snoozed'].includes(f.status)).map(f=>({...f,effective_due_at:f.snoozed_until||f.due_at})),tasks:visible(tasks,ws).filter(t=>!['completed','cancelled'].includes(t.status))});
  if(p[1]==='organizations'&&!p[2]&&method==='GET'){const q=(url.searchParams.get('q')||'').toLowerCase();return respond(res,200,visible(organizations,ws).filter(o=>!q||`${o.name} ${o.industry} ${o.country}`.toLowerCase().includes(q)).map(o=>enrichCounts(o,ws)));}
  if(p[1]==='organizations'&&!p[2]&&method==='POST'){const d=await body(req);const o={id:uid(),workspace_id:ws,status:'active',relationship_score:50,owner_id:'u1',owner_name:'Alex de Vries',...d};organizations.push(o);return respond(res,201,o);}
  if(p[1]==='organizations'&&p[2]){const o=visible(organizations,ws).find(x=>x.id===p[2]);if(!o)return respond(res,404,{error:'Account not found'});return respond(res,200,{organization:enrichCounts(o,ws),contacts:visible(contacts,ws).filter(c=>c.organization_id===o.id),activities:visible(activities,ws).filter(a=>a.organization_id===o.id),tasks:visible(tasks,ws).filter(t=>t.organization_id===o.id),follow_ups:visible(followUps,ws).filter(f=>f.organization_id===o.id),deals:visible(deals,ws).filter(d=>d.organization_id===o.id)});}
  if(p[1]==='contacts'&&!p[2]&&method==='GET'){let list=visible(contacts,ws);const q=(url.searchParams.get('q')||'').toLowerCase();const account=url.searchParams.get('account');const stage=url.searchParams.get('stage');const health=url.searchParams.get('health');if(q)list=list.filter(c=>`${c.first_name} ${c.last_name} ${c.email} ${c.job_title} ${c.organization_name}`.toLowerCase().includes(q));if(account)list=list.filter(c=>c.organization_id===account);if(stage)list=list.filter(c=>c.lifecycle_stage===stage);if(health==='at_risk')list=list.filter(c=>c.relationship_score<35);if(health==='attention')list=list.filter(c=>c.relationship_score>=35&&c.relationship_score<55);if(health==='healthy')list=list.filter(c=>c.relationship_score>=55);const page=Number(url.searchParams.get('page')||1),pageSize=Number(url.searchParams.get('pageSize')||25);return respond(res,200,{items:list.slice((page-1)*pageSize,page*pageSize).map(c=>contactOut(c,ws)),page,pageSize,total:list.length,pages:Math.max(1,Math.ceil(list.length/pageSize))});}
  if(p[1]==='contacts'&&!p[2]&&method==='POST'){const d=await body(req);const org=organizations.find(o=>o.id===d.organization_id);const c={id:uid(),workspace_id:ws,relationship_score:50,status:'active',owner_id:'u1',owner_name:'Alex de Vries',tags:[],...d,organization_name:org?.name||null};contacts.push(c);return respond(res,201,c);}
  if(p[1]==='contacts'&&p[2]){const c=visible(contacts,ws).find(x=>x.id===p[2]);if(!c)return respond(res,404,{error:'Contact not found'});if(method==='PATCH'){Object.assign(c,await body(req));return respond(res,200,c);}return respond(res,200,{contact:contactOut(c,ws),activities:visible(activities,ws).filter(a=>a.contact_id===c.id).sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)),tasks:visible(tasks,ws).filter(t=>t.contact_id===c.id),follow_ups:visible(followUps,ws).filter(f=>f.contact_id===c.id),deals:visible(deals,ws).filter(d=>d.primary_contact_id===c.id),attachments:[]});}
  if(p[1]==='activities'&&!p[2]&&method==='GET'){let list=visible(activities,ws);for(const [key,field] of [['account','organization_id'],['contact','contact_id'],['type','type']]){const v=url.searchParams.get(key);if(v)list=list.filter(x=>x[field]===v);}const q=(url.searchParams.get('q')||'').toLowerCase();if(q)list=list.filter(a=>`${a.subject} ${a.body} ${a.outcome}`.toLowerCase().includes(q));return respond(res,200,list.sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)));}
  if(p[1]==='activities'&&!p[2]&&method==='POST'){const d=await body(req);const c=contacts.find(x=>x.id===d.contact_id),o=organizations.find(x=>x.id===d.organization_id);const a={id:uid(),workspace_id:ws,user_id:'u1',user_name:'Alex de Vries',occurred_at:iso(),...d,contact_name:c?`${c.first_name} ${c.last_name}`:null,organization_name:o?.name||null};activities.push(a);if(c)c.last_contact_at=a.occurred_at;if(d.create_follow_up&&d.follow_up_due_at){followUps.push({id:uid(),workspace_id:ws,status:'open',owner_id:'u1',owner_name:'Alex de Vries',due_at:d.follow_up_due_at,contact_name:a.contact_name,organization_name:a.organization_name,contact_id:d.contact_id,organization_id:d.organization_id,...d.create_follow_up});}return respond(res,201,a);}
  if(p[1]==='deals'&&!p[2]&&method==='GET'){let list=visible(deals,ws);const account=url.searchParams.get('account');if(account)list=list.filter(d=>d.organization_id===account);return respond(res,200,list);}
  if(p[1]==='deals'&&!p[2]&&method==='POST'){const d=await body(req);const o=organizations.find(x=>x.id===d.organization_id),c=contacts.find(x=>x.id===d.primary_contact_id);const deal={id:uid(),workspace_id:ws,owner_id:'u1',owner_name:'Alex de Vries',...d,value:Number(d.value||0),probability:Number(d.probability||10),organization_name:o?.name,contact_name:c?`${c.first_name} ${c.last_name}`:null};deals.push(deal);return respond(res,201,deal);}
  if(p[1]==='deals'&&p[2]&&method==='PATCH'){const d=deals.find(x=>x.id===p[2]&&x.workspace_id===ws);Object.assign(d,await body(req));return respond(res,200,d);}
  if(p[1]==='tasks'&&!p[2]&&method==='GET'){let list=visible(tasks,ws);for(const [key,field] of [['account','organization_id'],['status','status'],['type','task_type'],['assignee','assignee_id']]){const v=url.searchParams.get(key);if(v)list=list.filter(x=>x[field]===v);}return respond(res,200,list);}
  if(p[1]==='tasks'&&!p[2]&&method==='POST'){const d=await body(req);const c=contacts.find(x=>x.id===d.contact_id),o=organizations.find(x=>x.id===d.organization_id),deal=deals.find(x=>x.id===d.deal_id),u=users.find(x=>x.id===d.assignee_id)||users[0];const t={id:uid(),workspace_id:ws,status:'open',...d,assignee_name:u.name,contact_name:c?`${c.first_name} ${c.last_name}`:null,organization_name:o?.name,deal_name:deal?.name};tasks.push(t);return respond(res,201,t);}
  if(p[1]==='tasks'&&p[2]&&method==='PATCH'){const t=tasks.find(x=>x.id===p[2]&&x.workspace_id===ws);Object.assign(t,await body(req));return respond(res,200,t);}
  if(p[1]==='follow-ups'&&!p[2]&&method==='GET'){let list=visible(followUps,ws);for(const [key,field] of [['account','organization_id'],['contact','contact_id'],['status','status'],['owner','owner_id']]){const v=url.searchParams.get(key);if(v)list=list.filter(x=>x[field]===v);}return respond(res,200,list.map(f=>({...f,effective_due_at:f.snoozed_until||f.due_at})));}
  if(p[1]==='follow-ups'&&!p[2]&&method==='POST'){const d=await body(req);const c=contacts.find(x=>x.id===d.contact_id),o=organizations.find(x=>x.id===d.organization_id),deal=deals.find(x=>x.id===d.deal_id),u=users.find(x=>x.id===d.owner_id)||users[0];const f={id:uid(),workspace_id:ws,status:'open',...d,owner_name:u.name,contact_name:c?`${c.first_name} ${c.last_name}`:null,organization_name:o?.name,deal_name:deal?.name};followUps.push(f);return respond(res,201,f);}
  if(p[1]==='follow-ups'&&p[2]&&p[3]==='complete'){const f=followUps.find(x=>x.id===p[2]&&x.workspace_id===ws);f.status='completed';f.completed_at=iso();const d=await body(req);if(d.log_activity){const c=contacts.find(x=>x.id===f.contact_id),o=organizations.find(x=>x.id===f.organization_id);activities.push({id:uid(),workspace_id:ws,user_id:'u1',user_name:'Alex de Vries',occurred_at:iso(),contact_id:f.contact_id,organization_id:f.organization_id,contact_name:c?`${c.first_name} ${c.last_name}`:null,organization_name:o?.name,...d.log_activity});}return respond(res,200,f);}
  if(p[1]==='follow-ups'&&p[2]&&p[3]==='snooze'){const f=followUps.find(x=>x.id===p[2]&&x.workspace_id===ws);const d=await body(req);f.status='snoozed';f.snoozed_until=d.until;return respond(res,200,f);}
  if(p[1]==='follow-ups'&&p[2]&&method==='PATCH'){const f=followUps.find(x=>x.id===p[2]&&x.workspace_id===ws);Object.assign(f,await body(req));return respond(res,200,f);}
  if(p[1]==='email'&&p[2]==='senders'&&!p[3]&&method==='GET')return respond(res,200,visible(emailSenders,ws).filter(s=>s.is_active));
  if(p[1]==='email'&&p[2]==='senders'&&!p[3]&&method==='POST'){const d=await body(req);const sender={id:uid(),workspace_id:ws,is_default:0,is_active:1,domain:String(d.email_address||'').split('@').at(-1),...d};emailSenders.push(sender);return respond(res,201,sender);}
  if(p[1]==='email'&&p[2]==='senders'&&p[3]&&method==='PATCH'){const sender=emailSenders.find(s=>s.id===p[3]&&s.workspace_id===ws);if(!sender)return respond(res,404,{error:'Sender identity not found'});Object.assign(sender,await body(req));return respond(res,200,sender);}
  if(p[1]==='email'&&p[2]==='messages'&&method==='GET'){let list=visible(emailMessages,ws);const account=url.searchParams.get('account'),status=url.searchParams.get('status'),sender=url.searchParams.get('sender'),q=(url.searchParams.get('q')||'').toLowerCase();if(account)list=list.filter(m=>m.organization_id===account);if(status)list=list.filter(m=>m.status===status);if(sender)list=list.filter(m=>m.sender_identity_id===sender);if(q)list=list.filter(m=>`${m.subject} ${m.from_email} ${m.organization_name||''} ${m.contact_name||''}`.toLowerCase().includes(q));return respond(res,200,list.sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,Number(url.searchParams.get('limit')||100)));}
  if(p[1]==='email'&&p[2]==='health'&&method==='GET')return respond(res,200,{ok:true,service_binding:true,provider_binding:true,service:'partnermarket-global-email-worker',checked_at:iso()});
  if(p[1]==='email'&&p[2]==='overview'&&method==='GET'){const account=url.searchParams.get('account');const list=visible(emailMessages,ws).filter(m=>!account||m.organization_id===account);const sent=list.filter(m=>m.status==='sent').length,failed=list.filter(m=>m.status==='failed').length,total=list.length;return respond(res,200,{window_days:Number(url.searchParams.get('days')||30),totals:{total,sent,failed,queued:list.filter(m=>m.status==='queued').length,recipients:list.reduce((sum,m)=>sum+Number(m.recipient_count||(m.to||[]).length),0),with_attachments:list.filter(m=>(m.attachments||[]).length).length,delivery_rate:total?Math.round(sent/total*1000)/10:0,failure_rate:total?Math.round(failed/total*1000)/10:0},senders:visible(emailSenders,ws).filter(s=>s.is_active).map(s=>({...s,total:list.filter(m=>m.sender_identity_id===s.id).length,sent:list.filter(m=>m.sender_identity_id===s.id&&m.status==='sent').length,failed:list.filter(m=>m.sender_identity_id===s.id&&m.status==='failed').length})),daily:[],failures:list.filter(m=>m.status==='failed').slice(0,8)});}
  if(p[1]==='email'&&p[2]==='send'&&method==='POST'){const d=await body(req);const sender=emailSenders.find(s=>s.id===d.sender_identity_id&&s.workspace_id===ws);if(!sender)return respond(res,400,{error:'Select an active sender identity'});const c=contacts.find(x=>x.id===d.contact_id&&x.workspace_id===ws)||contacts.find(x=>x.workspace_id===ws&&x.email?.toLowerCase()===String(d.to||'').toLowerCase());const organizationId=d.organization_id||c?.organization_id;const o=organizations.find(x=>x.id===organizationId&&x.workspace_id===ws);if(!o)return respond(res,400,{error:'Select the account this email belongs to'});if(c&&(c.email_opt_out||c.status==='do_not_contact'||c.consent_status==='withdrawn'))return respond(res,409,{error:'This contact has opted out of email communication'});const sentAt=iso();const message={id:uid(),workspace_id:ws,sender_identity_id:sender.id,contact_id:c?.id||null,organization_id:o.id,deal_id:d.deal_id||null,user_id:'u1',from_email:sender.email_address,from_name:sender.display_name,reply_to:sender.reply_to,to:[String(d.to||'').trim()],cc:String(d.cc||'').split(/[;,]/).map(x=>x.trim()).filter(Boolean),bcc:String(d.bcc||'').split(/[;,]/).map(x=>x.trim()).filter(Boolean),subject:d.subject,text_body:d.text_body,html_body:d.html_body,status:'sent',provider_message_id:'mock-'+uid(),sent_at:sentAt,created_at:sentAt,organization_name:o.name,contact_name:c?c.first_name+' '+c.last_name:null};emailMessages.push(message);activities.push({id:uid(),workspace_id:ws,contact_id:c?.id||null,organization_id:o.id,deal_id:d.deal_id||null,user_id:'u1',user_name:'Alex de Vries',contact_name:message.contact_name,organization_name:o.name,type:'email',direction:'outbound',subject:d.subject,body:d.text_body,outcome:'Sent',occurred_at:sentAt,metadata:{email_message_id:message.id,from:sender.email_address,to:message.to}});o.last_contact_at=sentAt;if(c)c.last_contact_at=sentAt;if(d.follow_up_due_at)followUps.push({id:uid(),workspace_id:ws,contact_id:c?.id||null,organization_id:o.id,deal_id:d.deal_id||null,owner_id:'u1',owner_name:'Alex de Vries',contact_name:message.contact_name,organization_name:o.name,title:d.follow_up_title||'Follow up: '+d.subject,channel:'email',status:'open',priority:d.follow_up_priority||'medium',due_at:d.follow_up_due_at,cadence:'none'});return respond(res,201,message);}
  if(p[1]==='analytics'){const as=visible(activities,ws),ds=visible(deals,ws),fs=visible(followUps,ws),ts=visible(tasks,ws);const group=(list,key)=>Object.values(list.reduce((m,x)=>{const k=x[key]||'other';m[k]||={ [key]:k,count:0};m[k].count++;return m;},{}));return respond(res,200,{activity_types:group(as,'type'),users:users.map(u=>({name:u.name,activities:as.filter(a=>a.user_id===u.id).length})),revenue_by_month:Array.from({length:6},(_,i)=>({month:new Date(now-(5-i)*30*864e5).toISOString().slice(0,7)+'-01',won_value:i===4?95000:0,won_count:i===4?1:0})),follow_up_stats:{total:fs.length,completed:fs.filter(f=>f.status==='completed').length,overdue:fs.filter(f=>['open','snoozed'].includes(f.status)&&new Date(f.snoozed_until||f.due_at)<new Date()).length},task_stats:{total:ts.length,completed:ts.filter(t=>t.status==='completed').length,overdue:ts.filter(t=>!['completed','cancelled'].includes(t.status)&&new Date(t.due_at)<new Date()).length},conversion:group(ds,'stage'),top_accounts:visible(organizations,ws).map(o=>enrichCounts(o,ws)).map(o=>({...o,contacts:o.contact_count,activities:as.filter(a=>a.organization_id===o.id).length,pipeline:o.pipeline_value}))});}
  if(p[1]==='search'){const q=(url.searchParams.get('q')||'').toLowerCase();return respond(res,200,{contacts:visible(contacts,ws).filter(c=>`${c.first_name} ${c.last_name} ${c.email}`.toLowerCase().includes(q)).slice(0,8),organizations:visible(organizations,ws).filter(o=>o.name.toLowerCase().includes(q)).slice(0,8),deals:visible(deals,ws).filter(d=>d.name.toLowerCase().includes(q)).slice(0,8)});}
  if(p[1]==='workspaces'&&!p[2]&&method==='POST'){const d=await body(req);const w={id:uid(),slug:String(d.name).toLowerCase().replace(/[^a-z0-9]+/g,'-'),member_role:'admin',is_default:0,...d};workspaces.push(w);return respond(res,201,w);}
  if(p[1]==='workspaces'&&p[2]&&method==='PATCH'){const w=workspaces.find(x=>x.id===p[2]);Object.assign(w,await body(req));return respond(res,200,w);}
  if(p[1]==='imports'&&p[2]==='contacts'){const d=await body(req);const lines=d.csv.trim().split(/\r?\n/);return respond(res,201,{id:uid(),row_count:Math.max(0,lines.length-1),success_count:Math.max(0,lines.length-1),failure_count:0,errors:[]});}
  if(p[1]==='exports'&&p[2]==='contacts'){const csv=['first_name,last_name,email,organization',...visible(contacts,ws).map(c=>`${c.first_name},${c.last_name},${c.email},${c.organization_name}`)].join('\n');return respond(res,200,csv,'text/csv; charset=utf-8');}
  return respond(res,404,{error:'API route not found'});
}

const server=createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost:8787');if(url.pathname==='/health')return respond(res,200,{ok:true,version:'2.3.0'});if(url.pathname.startsWith('/api/'))return handleApi(req,res,url);let path=normalize(url.pathname).replace(/^([.][.][/\\])+/, '');if(path==='/'||!extname(path))path='/index.html';try{const file=await readFile(join(root,path));const ext=extname(path);const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.csv':'text/csv; charset=utf-8'};respond(res,200,file,types[ext]||'application/octet-stream');}catch{const file=await readFile(join(root,'index.html'));respond(res,200,file,'text/html; charset=utf-8');}});
server.listen(8787,()=>console.log('PartnerMarket Global CRM V2.3 mock server running at http://localhost:8787'));
